[build]
  command = "rm -rf dist && mkdir dist && rsync -rv * dist --exclude ./dist"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@opentelemetry/instrumentation", "import-in-the-middle"]
  included_files = ["node_modules/@opentelemetry/instrumentation/**", "node_modules/import-in-the-middle/**"]
