[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@opentelemetry/instrumentation"]
  included_files = ["node_modules/@opentelemetry/instrumentation/**"]
