[build]
  command = "npm run build"
  publish = "dist"

[functions]
  included_files = ["node_modules/@opentelemetry/instrumentation/*", "node_modules/import-in-the-middle/*", "node_modules/acorn-import-attributes/*"]
